### ISSUE TITLE
webpack插件按照文档配置，build的时候报错

### ISSUE THREAD

**Issue by leiyily** [ice-lab/icestark#231]
配置：
"webpackPlugins": {
        "webpack/lib/ProvidePlugin": {
            "options": {
                "_": "lodash"
            }
        },
        "HtmlWebpackPlugin": {
            "before": "webpack/lib/ProvidePlugin"
        }
    }

报错： 
ERR! Invalid plugin configuration: plugin('webpack.ProvidePlugin').use(<Plugin>) was not called to specify the plugin 
Error: Invalid plugin configuration: plugin('webpack.ProvidePlugin').use(<Plugin>) was not called to specify the plugin
    at Object.toConfig (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_webpack-chain@6.5.1@webpack-chain/src/Plugin.js:60:15)
    at clean.Object.assign.plugins.plugins.values.map (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_webpack-chain@6.5.1@webpack-chain/src/Config.js:129:63)
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_webpack-chain@6.5.1@webpack-chain/src/Config.js:129:40)
    at configArr.map.v (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_@alib_build-scripts@0.1.30@@alib/build-scripts/lib/commands/build.js:53:60)
    at Array.map (<anonymous>)
    at module.exports (/Users/leiyi/Desktop/workprogram/gt-umacweb/node_modules/_@alib_build-scripts@0.1.30@@alib/build-scripts/lib/commands/build.js:53:37)

**Comment by leiyily** [comment]
<img width="543" alt="1610952445549_E1163CCD-4A0D-42A9-B5C8-43F8FBE9BD3B" src="https://user-images.githubusercontent.com/30883546/104884529-799ef780-59a1-11eb-9c1f-a51b1cf331a0.png">
<img width="1234" alt="1610952459990_495CFB96-013E-4137-BAA8-3DC4F50368E3" src="https://user-images.githubusercontent.com/30883546/104884542-7efc4200-59a1-11eb-8007-012249c5cd09.png">

**Comment by luhc228** [comment]
ice.js@1.15.0 已修复
