### ISSUE TITLE
Vue3  Hash模式加载失败

### ISSUE THREAD

**Issue by fulisadawang** [ice-lab/icestark#607]
vue3中主应用 子应用都使用hash模式加载会报错并且加载不出来。
vue-router.mjs:3420 Error: Invalid route component
    at extractComponentsGuards (vue-router.mjs:2035:27)
    at vue-router.mjs:3222:22
    
<img width="747" alt="image" src="https://user-images.githubusercontent.com/7625304/178218124-b3be93f6-0cff-4c47-9231-679382212eef.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/7625304/178218158-a7b74998-e494-408f-bc12-ef3b878ff8a4.png">
**
<img width="581" alt="image" src="https://user-images.githubusercontent.com/7625304/178218209-434291ed-6653-4d41-976f-313321e70c1c.png">
是否可以提供一个都是hash模式的demo 而且在使用了vue2主应用加载vue3 的子应用的时候也有不一样的地方
<img width="570" alt="image" src="https://user-images.githubusercontent.com/7625304/178218423-6794e5f8-74ad-424f-8bf0-0e93eb119cbf.png">
主应用y通过上面的加载才能加载

**Comment by 18311023368** [comment]
大佬们 这个问题 怎么处理啊

**Comment by 1340691923** [comment]
请问你解决了吗

**Comment by chaelaugh** [comment]
大佬解决了吗
